version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-sqs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-59kfglfdez4o"
s3_prefix = "lambda-sqs"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "CodeBucket=\"querof-labmbda-bucket\" function=\"lambda-sqs.zip\""
